import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { GenericLayout } from '@/layouts/Generic'
import { ClientProviderLayout } from '@/layouts/ClientProvider'
import { UseMeType } from '@/validations/validations'
import axios from 'axios'
import UserStoreInitializer from '@/store/initializer'
import { deleteCookie } from 'cookies-next'
import { redirect } from 'next/navigation'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-title',
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${inter.variable}`}>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <GenericLayout>
            <ClientProviderLayout>{children}</ClientProviderLayout>
          </GenericLayout>
        </ThemeProvider>
      </body>
    </html>
  )
}
